// SPDX-FileCopyrightText: 2026 SUSE LLC
//
// SPDX-License-Identifier: Apache-2.0

package templates

import (
	"bytes"
	"io"
	"testing"

	"github.com/uyuni-project/uyuni-tools/shared/testutils"
	"github.com/uyuni-project/uyuni-tools/shared/types"
)

// templateRenderer is a local interface to avoid importing shared/utils,
// which would cause an import cycle.
type templateRenderer interface {
	Render(wr io.Writer) error
}

func TestTemplatesRender(t *testing.T) {
	tests := []struct {
		name     string
		template templateRenderer
		expected string
	}{
		{
			name: "InspectTemplateData",
			template: InspectTemplateData{
				Values: []types.InspectData{
					types.NewInspectData("TEST_VAR", "echo 'hello'"),
				},
			},
			expected: `
# inspect.sh, generated by mgradm
echo "TEST_VAR=$(echo 'hello')"
exit 0
`,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var buf bytes.Buffer
			if err := tt.template.Render(&buf); err != nil {
				t.Errorf("%s render failed: %v", tt.name, err)
			}
			actual := buf.String()
			if tt.expected != "" && actual != tt.expected {
				diff := testutils.DiffStrings(tt.expected, actual)
				t.Errorf("%s render output mismatch:\n%s", tt.name, diff)
			}
		})
	}
}
