# SPDX-FileCopyrightText: 2024 SUSE LLC
#
# SPDX-License-Identifier: Apache-2.0

version: "2"
linters:
  enable:
    - dupl
    - errname
    - errorlint
    - godot
    - lll
    - misspell
    - revive
    - staticcheck
    - unparam
    - whitespace
  settings:
    gocyclo:
      min-complexity: 10
    govet:
      disable:
        - printf
    staticcheck:
      initialisms:
        # Default
        - ACL
        - API
        - ASCII
        - CPU
        - DNS
        - EOF
        - GUID
        - HTML
        - HTTP
        - HTTPS
        - ID
        - IP
        - JSON
        - RPC
        - SLA
        - SMTP
        - SQL
        - SSH
        - TCP
        - TLS
        - TTL
        - UDP
        - UI
        - GID
        - UID
        - UUID
        - URI
        - URL
        - UTF8
        - VM
        - XML
        - RTP
        - DB
        # Added
        - SCC
        - SSL
      dot-import-whitelist:
        - github.com/uyuni-project/uyuni-tools/shared/l10n
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - revive
        text: dot-imports
      - linters:
          - revive
        text: stutters
      - linters:
          - revive
        text: "meaningless package names"
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
  exclusions:
    generated: lax
