# SPDX-FileCopyrightText: 2024 SUSE LLC
#
# SPDX-License-Identifier: Apache-2.0

linters-settings:
  stylecheck:
    dot-import-whitelist:
      - github.com/uyuni-project/uyuni-tools/shared/l10n
  gofmt:
    simplify: true
  gocyclo:
    min-complexity: 10
  govet:
    disable:
      - printf

linters:
  enable:
    - unused
    - dupl
    - errcheck
    - errname
    - errorlint
    - godot
    - gofmt
    - goimports
    - gosimple
      #- gocyclo
    - ineffassign
    - govet
    - lll
    - misspell
    - staticcheck
    - stylecheck
    - unparam
    - unused
    - whitespace


