# SPDX-FileCopyrightText: 2024 SUSE LLC
#
# SPDX-License-Identifier: Apache-2.0
#
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
- repo: https://github.com/golangci/golangci-lint
  rev: v1.59.1
  hooks:
    - id: golangci-lint
      fail_fast: true
      stages:
        - pre-push

- repo: https://github.com/fsfe/reuse-tool
  rev: v4.0.3
  hooks:
    - id: reuse

- repo: https://github.com/cbosdo/gettext-go-lint
  rev: gettext-go-lint-0.1.1-0
  hooks:
    - id: lint
      args:
        - --keyword=L,NL,PL

- repo: local
  hooks:
  - id: check-localizable
    name: Check localizable strings
    entry: ./check_localizable
    files: '.*\.go'
    language: script
  - id: build
    name: Build
    fail_fast: true
    pass_filenames: false
    entry: ./pre-commit-build.sh
    language: script
    stages:
      - pre-push
  - id: build-all-tags
    name: Build with all tags
    fail_fast: true
    pass_filenames: false
    entry: ./pre-commit-build.sh
    language: script
    args:
      - -tags=nok8s,ptf
    stages:
      - pre-push
  - id: copyright-year
    name: Copyright year is up to date in changed files
    entry: ./update-copyright-year.sh
    language: script
    require_serial: true
