#!/bin/sh
#
# SPDX-FileCopyrightText: 2024 SUSE LLC
#
# SPDX-License-Identifier: Apache-2.0

res=0
grep -r . --include '*.go' --exclude '*_test.go' -n \
    -e 'fmt\.Errorf("[^"]\+"' \
    -e 'errors.New("[^"]\+"' \
    -e '\(Fatal\|Error\|Info\|Warn\)()\(\.Err(err)\)\?\.Msgf\?("' \
    -e '\.Flags()\.\(String\|Int\|Bool\)\(Slice\)\?\(Var\)\?P\?([^)]\+, \+"[^"]\+")' \
    -e '\(Short\|Long\|Title\): \+["`]'

if test $? -eq 0; then
    echo -e "Fix the non localizable strings\n"
    res=1
fi

grep -r . --include '*.go' --exclude '*_test.go' -n \
    -e '\(Trace\|Debug\)()\(\.Err(err)\)\?\.Msgf\?(P\?N\?L("' \

if test $? -eq 0; then
    echo -e "Trace and debug messages shouldn't be localizable\n"
    res=1
fi

grep -r . --include '*.go' --exclude '*_test.go' -n \
    -e '\(Short\|Long\): \+P\?N\?L(["`][a-z]'
if test $? -eq 0; then
    echo -e "Short and Long messages shouldn't start with a lowercase letter\n"
    res=1
fi

exit $res
