// SPDX-FileCopyrightText: 2025 SUSE LLC
//
// SPDX-License-Identifier: Apache-2.0

package utils

import (
	"path"

	"github.com/uyuni-project/uyuni-tools/shared/types"
)

// DBInspector inspects a running db container or its image.
type DBInspector struct {
	BaseInspector
}

// NewDBInspector creates a new ServerInspector generating the inspection script and data in scriptDir.
func NewDBInspector(scriptDir string) DBInspector {
	base := BaseInspector{
		Values: []types.InspectData{
			types.NewInspectData("image_pg_version",
				"echo $PG_MAJOR || true"),
		},
		ScriptDir: scriptDir,
		DataPath:  path.Join(InspectContainerDirectory, inspectDataFile),
	}
	return DBInspector{
		BaseInspector: base,
	}
}

// DBInspectData are data of the DB data.
type DBInspectData struct {
	ImagePgVersion string `mapstructure:"image_pg_version"`
}

// ReadInspectData parses the data generated by the server inspector.
func (i *DBInspector) ReadInspectData() (*DBInspectData, error) {
	return ReadInspectData[DBInspectData](path.Join(i.ScriptDir, inspectDataFile))
}
