// SPDX-FileCopyrightText: 2025 SUSE LLC
//
// SPDX-License-Identifier: Apache-2.0

package utils

import (
	"path"

	"github.com/uyuni-project/uyuni-tools/shared/types"
)

// ServerInspector inspects a running server container or its image.
type ServerInspector struct {
	BaseInspector
}

// NewServerInspector creates a new ServerInspector generating the inspection script and data in scriptDir.
func NewServerInspector(scriptDir string) ServerInspector {
	base := BaseInspector{
		Values: []types.InspectData{
			types.NewInspectData(
				"uyuni_release",
				"cat /etc/*release | grep 'Uyuni release' | cut -d ' ' -f3 || true"),
			types.NewInspectData(
				"suse_manager_release",
				`sed 's/.*(\([0-9.]\+\).*/\1/g' /etc/susemanager-release || true`),
			types.NewInspectData(
				"fqdn",
				`sed -n '/^java\.hostname/{s/^java\.hostname[[:space:]]*=[[:space:]]*\(.*\)/\1/;p}' /etc/rhn/rhn.conf || true`),
			types.NewInspectData("current_pg_version",
				"(psql -V | awk '{print $3}' | cut -d. -f1) || true"),
			types.NewInspectData("current_pg_version_not_migrated",
				"(test -e /var/lib/pgsql/data/data/PG_VERSION && cat /var/lib/pgsql/data/data/PG_VERSION) || true"),
			types.NewInspectData("db_user",
				`sed -n '/^db_user/{s/^db_user[[:space:]]*=[[:space:]]*\(.*\)/\1/;p}' /etc/rhn/rhn.conf || true`),
			types.NewInspectData("db_password",
				`sed -n '/^db_password/{s/^db_password[[:space:]]*=[[:space:]]*\(.*\)/\1/;p}' /etc/rhn/rhn.conf || true`),
			types.NewInspectData("db_name",
				`sed -n '/^db_name/{s/^db_name[[:space:]]*=[[:space:]]*\(.*\)/\1/;p}' /etc/rhn/rhn.conf || true`),
			types.NewInspectData("db_port",
				`sed -n '/^db_port/{s/^db_port[[:space:]]*=[[:space:]]*\(.*\)/\1/;p}' /etc/rhn/rhn.conf || true`),
			types.NewInspectData("db_host",
				`sed -n '/^db_host/{s/^db_host[[:space:]]*=[[:space:]]*\(.*\)/\1/;p}' /etc/rhn/rhn.conf || true`),
			types.NewInspectData("report_db_host",
				`sed -n '/^report_db_host/{s/^report_db_host[[:space:]]*=[[:space:]]*\(.*\)/\1/;p}' /etc/rhn/rhn.conf || true`),
		},
		ScriptDir: scriptDir,
		DataPath:  path.Join(InspectContainerDirectory, inspectDataFile),
	}
	return ServerInspector{
		BaseInspector: base,
	}
}

// CommonInspectData are data common between the migration source inspect and server inspector results.
type CommonInspectData struct {
	CurrentPgVersion            string `mapstructure:"current_pg_version"`
	CurrentPgVersionNotMigrated string `mapstructure:"current_pg_version_not_migrated"`
	DBUser                      string `mapstructure:"db_user"`
	DBPassword                  string `mapstructure:"db_password"`
	DBName                      string `mapstructure:"db_name"`
	DBPort                      int    `mapstructure:"db_port"`
	DBHost                      string `mapstructure:"db_host"`
	ReportDBHost                string `mapstructure:"report_db_host"`
}

// ServerInspectData are the data extracted by a server inspector.
type ServerInspectData struct {
	CommonInspectData  `mapstructure:",squash"`
	DBInspectData      `mapstructure:",squash"`
	UyuniRelease       string `mapstructure:"uyuni_release"`
	SuseManagerRelease string `mapstructure:"suse_manager_release"`
	Fqdn               string
}

// ReadInspectData parses the data generated by the server inspector.
func (i *ServerInspector) ReadInspectData() (*ServerInspectData, error) {
	return ReadInspectData[ServerInspectData](path.Join(i.ScriptDir, inspectDataFile))
}
