// SPDX-FileCopyrightText: 2024 SUSE LLC
//
// SPDX-License-Identifier: Apache-2.0

package utils

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path"
	"regexp"
	"strings"
	"time"

	"github.com/rs/zerolog"
	"github.com/rs/zerolog/log"
	. "github.com/uyuni-project/uyuni-tools/shared/l10n"
)

// GetSupportConfigPath returns the support config tarball path.
func GetSupportConfigPath(out string) string {
	re := regexp.MustCompile(`/var/log/scc_(.*?)\.txz`)
	return re.FindString(out)
}

// GetSupportConfigFileSaveName returns the support config file name.
func GetSupportConfigFileSaveName() string {
	hostname_b, err := RunCmdOutput(zerolog.DebugLevel, "hostname")
	hostname := "localhost"
	if err != nil {
		log.Warn().Err(err).Msg(L("Unable to detect hostname, using localhost"))
		hostname = strings.TrimSpace(string(hostname_b))
	}
	now := time.Now()
	return fmt.Sprintf("scc_%s_%s", hostname, now.Format("20060102_1504"))
}

/* CreateSupportConfigTarball will create a tarball in outputFolder with all the supportconfig
 * files generated by host and pods.
 */
func CreateSupportConfigTarball(outputFolder string, files []string) error {
	// Pack it all into a tarball
	log.Info().Msg(L("Preparing the tarball"))

	supportFileName := GetSupportConfigFileSaveName()
	supportFilePath := path.Join(outputFolder, fmt.Sprintf("%s.tar.gz", supportFileName))

	tarball, err := NewTarGz(supportFilePath)
	if err != nil {
		return err
	}

	for _, file := range files {
		if err := tarball.AddFile(file, path.Join(supportFileName, path.Base(file))); err != nil {
			return Errorf(err, L("failed to add %s to tarball"), path.Base(file))
		}
	}
	tarball.Close()
	return nil
}

// RunSupportConfigOnProxyHost will run supportconfig command on host machine.
func RunSupportConfigOnHost(dir string) ([]string, error) {
	var files []string
	extensions := []string{"", ".md5"}
	// Run supportconfig on the host if installed
	if _, err := exec.LookPath("supportconfig"); err == nil {
		out, err := RunCmdOutput(zerolog.DebugLevel, "supportconfig")
		if err != nil {
			return []string{}, Errorf(err, L("failed to run supportconfig on the host"))
		}
		tarballPath := GetSupportConfigPath(string(out))

		// Look for the generated supportconfig file
		if tarballPath != "" && FileExists(tarballPath) {
			for _, ext := range extensions {
				files = append(files, tarballPath+ext)
			}
		} else {
			return []string{}, errors.New(L("failed to find host supportconfig tarball from command output"))
		}
	} else {
		log.Warn().Msg(L("supportconfig is not available on the host, skipping it"))
	}

	systemdDump, err := createSystemdDump(dir)
	if err != nil {
		log.Warn().Msg(L("systemd file are not present, skipping them"))
	} else {
		files = append(files, systemdDump)
	}

	containerList, err := runningContainer()
	if err != nil {
		return files, err
	}
	if len(containerList) > 0 {
		for _, container := range containerList {
			inspectDump, err := runPodmanInspectCommand(dir, container)
			if err != nil {
				log.Warn().Msgf(L("cannot podman inspect %s"), container)
			}
			files = append(files, inspectDump)

			bindedFilesDump, err := dumpBindedFileCommand(dir, container)
			if err != nil {
				log.Warn().Msgf(L("cannot dump the binded files in %s"), container)
			}
			files = append(files, bindedFilesDump)

			logsDump, err := runPodmanLogsCommand(dir, container)
			if err != nil {
				log.Warn().Msgf(L("cannot podman logs %s"), container)
			}
			files = append(files, logsDump)
		}
	}

	return files, nil
}

func createSystemdDump(dir string) (string, error) {
	systemdSupportConfig, err := os.Create(path.Join(dir, "systemd-conf"))
	if err != nil {
		return "", Errorf(err, L("cannot create %s"), systemdSupportConfig.Name())
	}

	out, err := RunCmdOutput(zerolog.DebugLevel, "systemctl", "cat", "uyuni-*")
	if err != nil {
		return "", Errorf(err, L("cannot run systemctl cat uyuni-proxy-pod"))
	}
	defer systemdSupportConfig.Close()

	_, err = systemdSupportConfig.WriteString(string(out))
	if err != nil {
		return "", err
	}

	return systemdSupportConfig.Name(), nil
}
==== BASE ====

func runPodmanInspectCommand(dir string, container string) (string, error) {
	podmanInspectDump, err := os.Create(path.Join(dir, "inspect-"+container))
	defer podmanInspectDump.Close()
	if err != nil {
		return "", Errorf(err, L("cannot create %s"), podmanInspectDump)
	}

	out, err := RunCmdOutput(zerolog.DebugLevel, "podman", "inspect", container)
	if err != nil {
		return "", Errorf(err, L("cannot run podman inspect %s"), container)
	}

	_, err = podmanInspectDump.WriteString(string(out))
	if err != nil {
		return "", err
	}
	return podmanInspectDump.Name(), nil
}

func runPodmanLogsCommand(dir string, container string) (string, error) {
	podmanLogsDump, err := os.Create(path.Join(dir, "logs-"+container))
	if err != nil {
		return "", Errorf(err, L("cannot create %s"), podmanLogsDump)
	}

	out, err := RunCmdOutput(zerolog.DebugLevel, "podman", "logs", container)
	if err != nil {
		return "", Errorf(err, L("cannot run podman inspect %s"), container)
	}

	_, err = podmanLogsDump.WriteString(string(out))
	if err != nil {
		return "", err
	}
	return podmanLogsDump.Name(), nil
}

func runningContainer() ([]string, error) {
	containerList, err := RunCmdOutput(zerolog.DebugLevel, "podman", "ps", "-a", "--format={{ .Names }}")
	if err != nil {
		return []string{}, err
	}

	return strings.Split(strings.TrimSpace(string(containerList)), "\n"), nil
}
==== BASE ====
