// SPDX-FileCopyrightText: 2026 SUSE LLC
//
// SPDX-License-Identifier: Apache-2.0

package templates

import (
	"io"
	"text/template"

	apiTypes "github.com/uyuni-project/uyuni-tools/shared/api/types"
	"github.com/uyuni-project/uyuni-tools/shared/types"
)

const envTemplate = `# uyuni-server environment, generated by mgradm
{{ if .TZ }}
TZ="{{ .TZ }}"
{{ end }}
{{ if .Fqdn }}
UYUNI_HOSTNAME="{{ .Fqdn }}"
{{ end }}
{{ if .Email }}
EMAIL="{{ .Email }}"
{{ end }}
{{ if .EmailFrom }}
EMAILFROM="{{ .EmailFrom }}"
{{ end }}
{{ if .DB }}
DB_NAME="{{ .DB.Name }}"
DB_HOST="{{ .DB.Host }}"
DB_PORT="{{ .DB.GetPort }}"
{{ end }}
{{ if .ReportDN }}
REPORTDB_NAME="{{ .ReportDB.Name }}"
REPORTDB_HOST="{{ .ReportDB.Host }}"
REPORTDB_PORT="{{ .ReportDB.GetPort }}"
{{ end }}
{{ if not .DB.IsLocal }}
EXTERNALDB_PROVIDER=""
{{ end }}
{{ if .Debug }}
DEBUG_JAVA="{{ .Debug }}"
{{ end }}
{{ if .Org }}
ORGANIZATION="{{ .Org }}"
{{ end }}
{{ if .Admin }}
ADMIN_FIRSTNAME="{{ .Admin.FirstName }}"
ADMIN_LASTNAME="{{ .Admin.LastName }}"
{{ end }}
{{ if .HasMirror }}
MIRROR_PATH=/mirror
{{ end }}
`

// PodmanServiceTemplateData POD information to create systemd file.
type PodmanServiceEnvironmentTemplateData struct {
	TZ        string
	Fqdn      string
	Email     string
	EmailFrom string
	DB        types.DBFlags
	ReportDB  types.DBFlags
	Debug     bool
	Org       string
	Admin     apiTypes.User
	HasMirror bool
}

// Render will create the systemd configuration file.
func (data PodmanServiceEnvironmentTemplateData) Render(wr io.Writer) error {
	t := template.Must(template.New("service").Parse(envTemplate))
	return t.Execute(wr, data)
}
