// SPDX-FileCopyrightText: 2026 SUSE LLC
//
// SPDX-License-Identifier: Apache-2.0

package templates

import (
	"bytes"
	"testing"

	apiTypes "github.com/uyuni-project/uyuni-tools/shared/api/types"
	"github.com/uyuni-project/uyuni-tools/shared/testutils"
	"github.com/uyuni-project/uyuni-tools/shared/types"
	"github.com/uyuni-project/uyuni-tools/shared/utils"
)

func TestTemplatesRender(t *testing.T) {
	tests := []struct {
		name     string
		template utils.Template
		expected string
	}{
		{
			name: "AttestationServiceTemplateData",
			template: AttestationServiceTemplateData{
				NamePrefix:   "uyuni",
				Network:      "uyuni-network",
				DBUserSecret: "db-user-secret",
				DBPassSecret: "db-pass-secret",
			},
		},
		{
			name: "HubXmlrpcServiceTemplateData",
			template: HubXmlrpcServiceTemplateData{
				CaSecret:   "ca-secret",
				CaPath:     "/etc/pki/ca.crt",
				Ports:      []types.PortMap{utils.NewPortMap(2830)},
				NamePrefix: "uyuni",
				Network:    "uyuni-network",
				ServerHost: "uyuni-server",
			},
		},
		{
			name: "PgsqlServiceTemplateData",
			template: PgsqlServiceTemplateData{
				Volumes:         []types.VolumeMount{{Name: "var-pgsql", MountPath: "/var/lib/pgsql"}},
				NamePrefix:      "uyuni",
				Ports:           []types.PortMap{utils.NewPortMap(5432)},
				Network:         "uyuni-network",
				CaSecret:        "ca-secret",
				CaPath:          "/etc/pki/ca.crt",
				CertSecret:      "cert-secret",
				CertPath:        "/etc/pki/tls.crt",
				KeySecret:       "key-secret",
				KeyPath:         "/etc/pki/tls.key",
				AdminUser:       "admin-user",
				AdminPassword:   "admin-pass",
				ManagerUser:     "manager-user",
				ManagerPassword: "manager-pass",
				ReportUser:      "report-user",
				ReportPassword:  "report-pass",
			},
		},
		{
			name: "SalineServiceTemplateData",
			template: SalineServiceTemplateData{
				NamePrefix: "uyuni",
				Network:    "uyuni-network",
				Volumes:    []types.VolumeMount{{Name: "etc-salt", MountPath: "/etc/salt"}},
			},
		},
		{
			name: "PodmanServiceTemplateData",
			template: PodmanServiceTemplateData{
				Volumes:            []types.VolumeMount{{Name: "var-spacewalk", MountPath: "/var/spacewalk"}},
				NamePrefix:         "uyuni",
				Args:               "--arg value",
				Ports:              []types.PortMap{utils.NewPortMap(80)},
				Network:            "uyuni-network",
				CaSecret:           "ca-secret",
				CaPath:             "/etc/pki/ca.crt",
				DBCaSecret:         "db-ca-secret",
				DBCaPath:           "/etc/pki/db-ca.crt",
				CertSecret:         "cert-secret",
				CertPath:           "/etc/pki/tls.crt",
				KeySecret:          "key-secret",
				KeyPath:            "/etc/pki/tls.key",
				AdminUserSecret:    "uyuni-admin-user",
				AdminPassSecret:    "uyuni-admin-pass",
				DBUserSecret:       "uyuni-db-user",
				DBPassSecret:       "uyuni-db-pass",
				ReportDBUserSecret: "uyuni-reportdb-user",
				ReportDBPassSecret: "uyuni-reportdb-pass",
				SCCUserSecret:      "uyuni-scc-user",
				SCCPassSecret:      "uyuni-scc-pass",
				ServerEnvFile:      "/etc/systemd/system/uyuni-server.conf.d/server.env",
			},
			expected: `# uyuni-server.service, generated by mgradm
# Use an uyuni-server.service.d/local.conf file to override

[Unit]
Description=Uyuni server image container service
Wants=network.target
After=network-online.target
RequiresMountsFor=%t/containers

[Service]
Environment=PODMAN_SYSTEMD_UNIT=%n
Restart=on-success
ExecStartPre=/bin/rm -f %t/uyuni-server.pid %t/%n.ctr-id
ExecStartPre=/usr/bin/podman rm --ignore --force -t 10 uyuni-server
ExecStart=/bin/sh -c '/usr/bin/podman run \
	--conmon-pidfile %t/uyuni-server.pid \
	--cidfile=%t/%n.ctr-id \
	--cgroups=no-conmon \
	--shm-size=0 \
	--shm-size-systemd=0 \
	--sdnotify=conmon \
	-d \
	--name uyuni-server \
	--hostname uyuni-server.mgr.internal \
	--arg value \
	-p 80:80 \
	-v var-spacewalk:/var/spacewalk \
	--env-file=/etc/systemd/system/uyuni-server.conf.d/server.env \
	--network uyuni-network \
	--secret uyuni-db-user,type=env,target=MANAGER_USER \
	--secret uyuni-db-pass,type=env,target=MANAGER_PASS \
	--secret uyuni-reportdb-user,type=env,target=REPORT_DB_USER \
	--secret uyuni-reportdb-pass,type=env,target=REPORT_DB_PASS \
	--secret ca-secret,type=mount,target=/etc/pki/ca.crt \
	--secret ca-secret,type=mount,target=/usr/share/susemanager/salt/certs/RHN-ORG-TRUSTED-SSL-CERT \
	--secret ca-secret,type=mount,target=/srv/www/htdocs/pub/RHN-ORG-TRUSTED-SSL-CERT \
	--secret cert-secret,type=mount,target=/etc/pki/tls.crt \
	--secret key-secret,type=mount,target=/etc/pki/tls.key \
	--secret db-ca-secret,type=mount,target=/etc/pki/db-ca.crt \
	--secret uyuni-scc-user,type=env,target=SCC_USER \
	--secret uyuni-scc-pass,type=env,target=SCC_PASS \
	--secret uyuni-admin-user,type=env,target=ADMIN_USER \
	--secret uyuni-admin-pass,type=env,target=ADMIN_PASS \
	--health-on-failure=stop \
	${PODMAN_EXTRA_ARGS} ${UYUNI_IMAGE}'

ExecStop=-/usr/bin/podman exec \
    uyuni-server \
    /bin/bash -c 'spacewalk-service stop'
ExecStop=/usr/bin/podman stop \
	--ignore -t 10 \
	--cidfile=%t/%n.ctr-id
ExecStopPost=/usr/bin/podman rm \
	-f \
	--ignore -t 10 \
	--cidfile=%t/%n.ctr-id

PIDFile=%t/uyuni-server.pid
TimeoutStopSec=180
TimeoutStartSec=900
Type=forking

[Install]
WantedBy=multi-user.target default.target
`,
		},
		{
			name: "TFTPDTemplateData",
			template: TFTPDTemplateData{
				Network:    "uyuni-network",
				CaSecret:   "ca-secret",
				ServerFQDN: "uyuni.test.org",
			},
		},
		{
			name: "ServerEnvironmentData",
			template: PodmanServiceEnvironmentTemplateData{
				TZ:        "GMT",
				Fqdn:      "uyuni-server.example.com",
				Email:     "admin@example.com",
				EmailFrom: "notifications@example.com",
				DB:        &types.DBFlags{Host: "db", Name: "mlm", Port: 0},
				ReportDB:  &types.DBFlags{Host: "reportdb", Name: "reportdb"},
				Debug:     false,
				Org:       "Example.com",
				Admin:     &apiTypes.User{FirstName: "Test", LastName: "Admin"},
				HasMirror: false,
			},
			expected: `# uyuni-server environment, generated by mgradm
TZ=GMT
UYUNI_HOSTNAME=uyuni-server.example.com
EMAIL=admin@example.com
EMAILFROM=notifications@example.com
MANAGER_DB_NAME=mlm
MANAGER_DB_HOST=db
MANAGER_DB_PORT=5432
REPORT_DB_NAME=reportdb
REPORT_DB_HOST=reportdb
REPORT_DB_PORT=5432
ORGANIZATION=Example.com
ADMIN_FIRSTNAME=Test
ADMIN_LASTNAME=Admin`,
		},
		{
			name: "ServerEnvironmentDataExternalDB",
			template: PodmanServiceEnvironmentTemplateData{
				TZ:        "GMT",
				Fqdn:      "uyuni-server.example.com",
				Email:     "admin@example.com",
				EmailFrom: "notifications@example.com",
				DB:        &types.DBFlags{Host: "db.example.com", Name: "mlm", Port: 5431, Provider: "aws"},
				ReportDB:  &types.DBFlags{Host: "reportdb.example.com", Name: "reportdb"},
				Debug:     false,
				Org:       "My Example.com",
				Admin:     &apiTypes.User{FirstName: "Test", LastName: "Admin"},
				HasMirror: false,
			},
			expected: `# uyuni-server environment, generated by mgradm
TZ=GMT
UYUNI_HOSTNAME=uyuni-server.example.com
EMAIL=admin@example.com
EMAILFROM=notifications@example.com
MANAGER_DB_NAME=mlm
MANAGER_DB_HOST=db.example.com
MANAGER_DB_PORT=5431
EXTERNALDB_PROVIDER=aws
REPORT_DB_NAME=reportdb
REPORT_DB_HOST=reportdb.example.com
REPORT_DB_PORT=5432
ORGANIZATION=My Example.com
ADMIN_FIRSTNAME=Test
ADMIN_LASTNAME=Admin`,
		},
		{
			name:     "ServerEnvironmentEmptyData",
			template: PodmanServiceEnvironmentTemplateData{},
			expected: "",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var buf bytes.Buffer
			if err := tt.template.Render(&buf); err != nil {
				t.Errorf("%s render failed: %v", tt.name, err)
			}
			actual := buf.String()
			if tt.expected != "" && actual != tt.expected {
				diff := testutils.DiffStrings(tt.expected, actual)
				t.Errorf("%s render output mismatch:\n%s", tt.name, diff)
			}
		})
	}
}
