// SPDX-FileCopyrightText: 2026 SUSE LLC
//
// SPDX-License-Identifier: Apache-2.0

package templates

import (
	"io"
	"text/template"
)

const tftpdTemplate = `# uyuni-tftpd.service, generated by mgradm
# Use an uyuni-tftpd.service.d/local.conf file to override

[Unit]
Description=Uyuni tftpd container service
Wants=network.target
After=network-online.target
After=uyuni-server.service

[Service]
Environment=PODMAN_SYSTEMD_UNIT=%n
Restart=on-failure
ExecStartPre=/bin/rm -f %t/uyuni-tftpd.pid %t/uyuni-tftpd.ctr-id

ExecStart=/usr/bin/podman run \
	--conmon-pidfile %t/uyuni-tftpd.pid \
	--cidfile %t/uyuni-tftpd.ctr-id \
	--cgroups=no-conmon \
	--replace -d \
	-p 69:69/udp \
	--secret {{ .CaSecret }},type=mount,target=/etc/uyuni/ca.crt \
	--name uyuni-tftpd \
	--network {{ .Network }} \
	${UYUNI_TFTPD_IMAGE} \
	/usr/bin/tftp_wrapper.py \
		--httpHost {{ .ServerFQDN }} \
		--proxyFqdn {{ .ServerFQDN }} \
		--serverFqdn {{ .ServerFQDN }}


ExecStop=/usr/bin/podman stop --ignore --cidfile %t/uyuni-tftpd.ctr-id -t 10
ExecStopPost=/usr/bin/podman rm --ignore -f --cidfile %t/uyuni-tftpd.ctr-id
PIDFile=%t/uyuni-tftpd.pid
TimeoutStopSec=60
Type=forking

[Install]
WantedBy=multi-user.target default.target
`

// TFTPDTemplateData represents information used to create TFTPD systemd configuration file.
type TFTPDTemplateData struct {
	CaSecret   string
	Network    string
	ServerFQDN string
}

// Render will create the TFTPD systemd configuration file.
func (data TFTPDTemplateData) Render(wr io.Writer) error {
	t := template.Must(template.New("service").Parse(tftpdTemplate))
	return t.Execute(wr, data)
}
